# Define which image to base FROM

# Create application folder in image

# Assign application folder as WORKDIR

# Copy ./package.json from host to WORKDIR

# Run yarn to install dependencies

# copy sroucecode from ./src to WORKDIR/src

# Run command (CMD) to run start script in package.json

# Expose Image port